# Module manifest for module 'Sixel'
# Generated by: trackd
# Generated on: 2024-10-09

@{
    RootModule           = 'Sixel.psm1'
    ModuleVersion        = '0.2.5'
    CompatiblePSEditions = 'Core'
    PowerShellVersion    = '7.4'
    GUID                 = '95f4627c-f8f5-43d5-824b-4c356737f87b'
    Author               = 'trackd, ShaunLawrie'
    Copyright            = '(c) trackd. All rights reserved.'
    Description          = 'Convert images to Sixel format and display them in the terminal, Requires a terminal with Sixel support. (Windows Terminal v1.22.2912.0 or later), Inline Image Protocol or Kitty Graphics support.'
    CmdletsToExport      = @('ConvertTo-Sixel', 'ConvertTo-SixelGif')
    AliasesToExport      = @('cts', 'ConvertTo-InlineImage','gif')
    FormatsToProcess     = @('Sixel.format.ps1xml')
    TypesToProcess       = @('Sixel.types.ps1xml')
    PrivateData          = @{
        PSData = @{
            Tags         = @(
                'Sixel',
                'Terminal',
                'Graphics',
                'Image',
                'ConsoleImage',
                'InlineImageProtocol',
                'KittyGraphicsProtocol'
            )
            LicenseUri   = 'https://github.com/trackd/Sixel/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/trackd/Sixel'
            ReleaseNotes = @'
            0.2.5 - bugfix, cleanup, added experimental support for inline image protocol and Kitty Graphics Protocol.
            0.2.0 - Added better scaling, changes -Width to use cell width instead.
            0.1.0 - Initial release.
'@
        }
    }
    # A missing or $null entry is equivalent to specifying the wildcard *. declare unused with @() for better perf.
    FunctionsToExport    = @()
    VariablesToExport    = @()
}
